# Generated by Django 5.1.1 on 2024-09-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examineeprofile',
            name='fullname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='examineeprofile',
            name='number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
