# Generated by Django 5.1.1 on 2024-09-25 14:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_examineeprofile_fullname_examineeprofile_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='examineeProfile',
            new_name='Profile',
        ),
    ]
