# Generated by Django 5.1.1 on 2024-09-30 13:25

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_customer_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
