# Generated by Django 5.1.1 on 2024-09-28 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendcourse',
        ),
    ]
