# Generated by Django 5.1.1 on 2024-09-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_delete_attendcourse'),
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='questions',
            field=models.ManyToManyField(related_name='courses', to='question.question'),
        ),
        migrations.AddField(
            model_name='coursetype',
            name='question',
            field=models.ManyToManyField(to='question.question'),
        ),
    ]
