# Generated by Django 5.1.1 on 2024-09-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_questions_coursetype_question'),
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='questions',
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('questions', models.ManyToManyField(related_name='exams', to='question.question')),
            ],
        ),
    ]
