# Generated by Django 5.1.1 on 2024-09-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_remove_course_questions_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='exams',
            field=models.ManyToManyField(related_name='courses', to='course.exam'),
        ),
    ]
