# Generated by Django 5.1.1 on 2024-09-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_course_exams'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='details',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
