# Generated by Django 5.1.1 on 2024-09-28 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='name',
            new_name='question_text',
        ),
    ]
