# Generated by Django 5.1.1 on 2024-09-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_rename_text_option_four_question_a_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='a_img',
            new_name='a_image',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='b_img',
            new_name='b_image',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='c_img',
            new_name='c_image',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='d_img',
            new_name='d_image',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('audio', 'Audio'), ('text', 'Text'), ('image', 'Image'), ('mixed', 'Mixed')], max_length=50),
        ),
    ]
