# Generated by Django 5.1.1 on 2024-09-29 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_rename_a_img_question_a_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('audio', 'Audio'), ('text', 'Text'), ('image', 'Image')], max_length=50),
        ),
    ]
