# Generated by Django 5.1.1 on 2024-09-30 13:20

import question.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_alter_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_audio',
            field=models.FileField(blank=True, null=True, upload_to='audios/', validators=[question.validators.validate_audio_file_extension]),
        ),
        migrations.AddField(
            model_name='question',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', validators=[question.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='question',
            name='a_audio',
            field=models.FileField(blank=True, null=True, upload_to='audios/', validators=[question.validators.validate_audio_file_extension]),
        ),
        migrations.AlterField(
            model_name='question',
            name='a_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', validators=[question.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='question',
            name='ans',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='b_audio',
            field=models.FileField(blank=True, null=True, upload_to='audios/', validators=[question.validators.validate_audio_file_extension]),
        ),
        migrations.AlterField(
            model_name='question',
            name='b_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', validators=[question.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='question',
            name='c_audio',
            field=models.FileField(blank=True, null=True, upload_to='audios/', validators=[question.validators.validate_audio_file_extension]),
        ),
        migrations.AlterField(
            model_name='question',
            name='c_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='d_audio',
            field=models.FileField(blank=True, null=True, upload_to='audios/', validators=[question.validators.validate_audio_file_extension]),
        ),
        migrations.AlterField(
            model_name='question',
            name='d_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', validators=[question.validators.validate_image_file_extension]),
        ),
    ]
